apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: witty-reindeer-python 
  janus-idp.io/tekton: witty-reindeer-python
  backstage.io/kubernetes-id: witty-reindeer-python
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: witty-reindeer-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  