apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: witty-reindeer-python
  janus-idp.io/tekton: witty-reindeer-python
  backstage.io/kubernetes-id: witty-reindeer-python
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: witty-reindeer-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
